/***************************************************************
** Program name: Final.cpp
** Author:       Andrew Wilson
** Date:         Mar 11, 2019
** Description:  This is the implementation file for ASCII graphics the final project
**
** Refernce:     https://stackoverflow.com/a/41768860
** Generated by: http://patorjk.com/software/taag/#p=display&f=Doom&t=Rocket%20Escape
***************************************************************/
#include <iostream>
#include <string>
#include "headerGraphics.hpp"

void titleTest()
{
    std::cout << R"~(

______           _        _     _____                         
| ___ \         | |      | |   |  ___|                        
| |_/ /___   ___| | _____| |_  | |__ ___  ___ __ _ _ __   ___ 
|    // _ \ / __| |/ / _ \ __| |  __/ __|/ __/ _` | '_ \ / _ \
| |\ \ (_) | (__|   <  __/ |_  | |__\__ \ (_| (_| | |_) |  __/
\_| \_\___/ \___|_|\_\___|\__| \____/___/\___\__,_| .__/ \___|
                                                  | |         
                                                  |_|         
)~";

}